server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    url: jdbc:mysql:///reggie?useSSL=false
    username: "root"
    password: "yang269518"
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 192.168.75.129
      port: 6379
      password: root@123456
      database: 0 #操作的是0号数据库

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

raggie:
  path: D:\img\

